name: keeper
description: "Keeper AI - your universal AI-powered knowledge assistant."
publish_to: 'none'
version: 1.0.17+1011

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  google_sign_in: 6.3.0
  cloud_firestore: ^6.7.1
  uuid: ^4.6.0
  file_picker: 10.3.8
  supabase_flutter: ^2.16.0
  url_launcher: ^6.3.2
  syncfusion_flutter_pdf: ^33.2.13
  google_mlkit_text_recognition: ^0.16.0
  firebase_ai: ^3.14.1
  http: ^1.5.0
  image_picker: ^1.2.3
  image: ^4.8.0
  path_provider: ^2.1.5
  local_auth: ^2.3.0
  flutter_secure_storage: ^10.3.1
  cryptography: ^2.9.0
  share_plus: ^12.0.1
  flutter_math_fork: ^0.7.4
  flutter_local_notifications: ^19.4.2
  shared_preferences: ^2.5.3
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  speech_to_text: ^7.3.0
  syncfusion_flutter_pdfviewer: ^33.2.13
  firebase_app_check: ^0.4.5+2
  in_app_purchase: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.8

flutter:
  uses-material-design: true
flutter_native_splash:
  color: "#071426"
  android: true
  ios: true
  web: false
  fullscreen: true
  android_12:
    color: "#071426"
