class AiSopGeneratorService {
  // Generate SOP

  String generateSOP(String documentText) {
    return '''
STANDARD OPERATING PROCEDURE

--------------------------------

1. Objective

Automatically generated by Keeper AI.

--------------------------------

2. Description

$documentText

--------------------------------

3. Important Steps

- Step 1
- Step 2
- Step 3

--------------------------------

4. Responsibilities

- Assigned User
- Department
- Organization

--------------------------------

5. Notes

Generated using Keeper AI.

--------------------------------

6. Future Improvements

- Can be edited manually.
- Can be added to Knowledge Base.

''';
  }
}
