// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNnJr__rLbU7V8h2q0yuCEGkelKETqQyU',
    appId: '1:809938504753:web:2ee0286730be892110d910',
    messagingSenderId: '809938504753',
    projectId: 'keeper-ai-4edcd',
    authDomain: 'keeper-ai-4edcd.firebaseapp.com',
    storageBucket: 'keeper-ai-4edcd.firebasestorage.app',
    measurementId: 'G-508TP9VZWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7rTEFFZucrc0zmv5_TU3RPHNUcmyXry0',
    appId: '1:809938504753:android:4c82dd56f01bcac310d910',
    messagingSenderId: '809938504753',
    projectId: 'keeper-ai-4edcd',
    storageBucket: 'keeper-ai-4edcd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpNOHMbbkMuJvCIFclUMus8kwvTxLvJyY',
    appId: '1:809938504753:ios:0ce889eba6e389fa10d910',
    messagingSenderId: '809938504753',
    projectId: 'keeper-ai-4edcd',
    storageBucket: 'keeper-ai-4edcd.firebasestorage.app',
    iosBundleId: 'com.example.keeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpNOHMbbkMuJvCIFclUMus8kwvTxLvJyY',
    appId: '1:809938504753:ios:0ce889eba6e389fa10d910',
    messagingSenderId: '809938504753',
    projectId: 'keeper-ai-4edcd',
    storageBucket: 'keeper-ai-4edcd.firebasestorage.app',
    iosBundleId: 'com.example.keeper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNnJr__rLbU7V8h2q0yuCEGkelKETqQyU',
    appId: '1:809938504753:web:93e7e1d477c9144610d910',
    messagingSenderId: '809938504753',
    projectId: 'keeper-ai-4edcd',
    authDomain: 'keeper-ai-4edcd.firebaseapp.com',
    storageBucket: 'keeper-ai-4edcd.firebasestorage.app',
    measurementId: 'G-X3NDD4CYMY',
  );
}
